Added support for VCN Native endpoint
oracle-terraform-modules/terraform-oci-oke pull request #271
Opened 2021-03-18 11:25 UTC by hyder

* Simplified security lists                                                                                                                                                                   
*  Added a subnet for control plane                                                                                                                                                    
* Added 2 parameters                                                                                                                                                                          
* Updated default kubernetes version                                                                                                                                                     
* Updated terraform options doc

2021-03-18 11:33 UTC, hyder commented
Test cases:


endpoint | worker | lb
-- | -- | --
public | public | public
public | private | public
public | private | private
public | private | both
  |   |  
private | public | public
private | private | public
private | private | private
private | private | both

2021-03-24 10:01 UTC, kral2 commented
I would suggest [using imperative mood](https://chris.beams.io/posts/git-commit/#imperative) for issue and commit messages:

- added -> add
- simplified -> simplify

That will help in the long run.

2021-03-24 16:59 UTC, kral2 requested changes

2021-03-24 16:59 UTC, kral2 commented on modules/okenetwork/outputs.tf
> +    "cp", join(",", oci_core_subnet.cp.*.id),
This splat expression syntax is legacy (attribute-only). You should switch to the current splat expression syntax.

```suggestion
    "cp", join(",", oci_core_subnet.cp[*].id),
```

Same suggestion from line 6 to 9.

2021-03-25 01:04 UTC, kral2 submitted a review, later dismissed

2021-03-29 21:40 UTC, merged