Updated docs for cloud-init
oracle-terraform-modules/terraform-oci-oke pull request #554
Opened 2022-08-13 13:11 UTC by hyder

Closes #537 
Authored by @33percent

2022-08-22 00:12 UTC, hyder commented
Updated PR from #541

2022-08-22 23:29 UTC, Djelibeybi requested changes

2022-08-22 23:29 UTC, Djelibeybi commented on README.adoc
> +* {uri-cloudinit}[Configuring Cloudinit]
This should be `cloud-init` (with a hyphen)

2022-08-22 23:29 UTC, Djelibeybi commented on docs/cloudinit.adoc
> +  np3 = "/tmp/np3cloudinit.sh"
```suggestion
  np1 = "/tmp/np1_cloud-init.sh"
  np3 = "/tmp/np3_cloud-init.sh"
```

2022-08-22 23:29 UTC, Djelibeybi commented on docs/cloudinit.adoc
> +cloudinit_nodepool_common = "/tmp/commoncloudinit.sh"
```suggestion
cloudinit_nodepool_common = "/tmp/cloudinit_nodepool_common.sh"
```

This makes it easier to match filename to purpose.

2022-08-22 23:29 UTC, Djelibeybi commented on docs/cloudinit.adoc
> +In the above example, node pool `np1` and `np3` will use `/tmp/np1cloudinit.sh` and `/tmp/np3cloudinit.sh` respectively for their cloud-init.
```suggestion
In the above example, node pool `np1` and `np3` will use `/tmp/np1_cloud-init.sh` and `/tmp/np3_cloud-init.sh` respectively for their cloud-init. 
```

2022-08-23 01:57 UTC, Djelibeybi submitted a review, later dismissed

2022-08-23 02:27 UTC, Djelibeybi approved these changes

2022-08-23 08:08 UTC, merged