Bug in NSG rule for health check? (incorrect direction, or incorrect description?)
oracle-terraform-modules/terraform-oci-oke pull request #891
Opened 2024-02-05 14:43 UTC by syedthameem85

Resolves #820

2024-02-06 02:44 UTC, hyder commented on modules/network/nsg-workers.tf
> +      "Allow TCP egress to workers for health check from OKE control plane" : {
This should be Allow TCP egress to OKE control plane from workers for health check

2024-02-06 02:45 UTC, hyder requested changes
please review the recommended changes

2024-02-06 15:24 UTC, syedthameem85 commented
@hyder -The change has already been done and can be merged.

2024-02-06 15:26 UTC, hyder commented
> @hyder -The change has already been done and can be merged.

your description is still incorrect.

2024-02-06 23:20 UTC, syedthameem85 commented
@hyder  - " Allow TCP egress to OKE control plane from workers for health check"  Is this the correct description ?

2024-02-08 05:29 UTC, hyder approved these changes
Approved

2024-02-08 05:30 UTC, merged