docs: Added documentation for oci load balancer annotations
oracle-terraform-modules/terraform-oci-oke pull request #976
Opened 2024-12-20 00:57 UTC by ddevadat

Added the reference documentation for oci loadbalancer annotations

This PR is for adding documentation reference for the supported oci loadbalancer annotations

2025-01-05 22:14 UTC, hyder commented on docs/src/guide/load-balancer-annotations.md
> +This file defines a list of [Service][4] `type: LoadBalancer` annotations which are
Don't just copy from the OCI CCM docs. This will be published to github pages and not accessed by file. Rework the docs with publishing in mind.

2025-01-05 22:15 UTC, hyder commented on docs/src/guide/load-balancer-annotations.md
> +supported by the `oci-cloud-controller-manager`.
Please add link to OCI CCM repo.

2025-01-05 22:17 UTC, hyder commented on docs/src/guide/load-balancer-annotations.md
> +## Load balancer Type Annotation
Re-orgnanize the annotations by api group and pay particular attention to sec list vs nsg.

2025-01-05 22:18 UTC, hyder requested changes
Please review the comments and update the doc.

2026-09-11 12:58 UTC, robo-cap commented
no longer relevant.

For the full, updated list of annotations supported with Load Balancers services, please check this page:
https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengcreatingloadbalancer_topic-Summaryofannotations.htm

2026-09-11 12:58 UTC, closed without merging